title: Sociedade Uni√£o Sintrense
logo: /assets/img/logo.jpg
description: Cultura, teatro e vida associativa em Sintra.
lang: pt-PT

# GitHub Pages compatible theme (easy to swap)
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Show these pages in the header (minima)
header_pages:
  - agenda/index.md
  - oferta/index.md
  - noticias-e-atividades/index.md
  - teatro-uniao/index.md
  - torne-se-socio/index.md
  - contacte-nos/index.md

# Keep pretty URLs (/pasta/)
permalink: pretty
