title: Sociedade União Sintrense
description: Site oficial da Sociedade União Sintrense
logo: /assets/img/logo.png

theme: jekyll-theme-minimal
#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one

url: "https://vascoribeiropereira.github.io"
baseurl: "/sus-site"

# opcional mas útil
markdown: kramdown
