title: Sociedade União Sintrense
description: Site oficial da Sociedade União Sintrense

theme: minimal

url: "https://vascoribeiropereira.github.io"
baseurl: "/sus-site"

# opcional mas útil
markdown: kramdown
